"""
分析サービス — インデックス構築・ハイブリッドファイル読み込みの責務を担う。
ヒューリスティックサマリー（LLM不要な自明なファイル）と
LLMバッチ処理（複数ファイルを1回のLLM呼び出しで処理）を組み合わせて
インデックス構築を高速化する。
"""

from __future__ import annotations

import ast
import logging
import os
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path
from typing import Callable, Dict, Generator, List, Optional, Tuple

from localforge.application.context_service import ContextService
from localforge.domain.exceptions import IndexBuildError
from localforge.domain.models import (
    ChunkStrategy,
    FileChunk,
    GenerationLogEntry,
    ProjectIndex,
)
from localforge.infrastructure.filesystem_adapter import (
    CODE_EXTENSIONS,
    FileSystemAdapter,
)
from localforge.infrastructure.index_adapter import IndexAdapter
from localforge.infrastructure.ollama_client import OllamaClient
from localforge.infrastructure.vector_adapter import VectorAdapter

logger = logging.getLogger(__name__)

# ハイブリッド戦略のしきい値（行数）
_HYBRID_THRESHOLD = 350
# ハイブリッド戦略: 先頭の行数
_HYBRID_HEAD = 150
# ハイブリッド戦略: 末尾の行数
_HYBRID_TAIL = 150
# 設定・データファイルの拡張子（LLMサマリー不要）
_HEURISTIC_EXTENSIONS = frozenset({
    ".json", ".yaml", ".yml", ".toml", ".ini", ".cfg",
    ".md", ".txt", ".rst", ".lock", ".env",
    ".gitignore", ".dockerignore", ".gitattributes", ".editorconfig",
    # アセット・バイナリ系（LLMサマリー不要）
    ".svg", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico",
    ".woff", ".woff2", ".ttf", ".eot",
    ".map", ".snap", ".csv", ".xml",
})
# ロックファイル名（依存関係のロックファイル）
_LOCK_FILE_NAMES = frozenset({
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "poetry.lock", "Pipfile.lock", "Cargo.lock",
    "composer.lock", "Gemfile.lock", "go.sum",
})
# この実質行数以下のファイルはLLMを使わない
_HEURISTIC_LINE_THRESHOLD = 20
# ヒューリスティック処理中にN件ごとにディスクへ中間保存する
_INCREMENTAL_SAVE_INTERVAL = 50
# .localforgeディレクトリ名
_LOCALFORGE_DIR = ".localforge"
# 自動生成ファイルの検出パターン（ファイル先頭5行で検索）
_AUTO_GENERATED_PATTERNS = re.compile(
    r"(@generated|DO NOT EDIT|Code generated by|AUTO-GENERATED|"
    r"autogenerated|This file was generated|Generated by)",
    re.IGNORECASE,
)


def _detect_language(path: Path) -> str:
    """
    ファイルの拡張子から言語を推定する。

    Args:
        path: ファイルパス

    Returns:
        言語名文字列
    """
    ext_map = {
        ".py": "python", ".js": "javascript", ".ts": "typescript",
        ".jsx": "javascript", ".tsx": "typescript", ".go": "go",
        ".rs": "rust", ".java": "java", ".html": "html",
        ".css": "css", ".scss": "css", ".vue": "vue",
        ".rb": "ruby", ".php": "php", ".cs": "csharp",
        ".sh": "bash", ".yaml": "yaml", ".yml": "yaml",
        ".toml": "toml", ".json": "json", ".sql": "sql",
        ".md": "markdown",
    }
    return ext_map.get(path.suffix.lower(), "text")


def _extract_python_landmarks(source: str) -> List[str]:
    """
    ASTを使用してPythonソースコードの構造的ランドマーク（クラス・関数・インポート）を抽出する。
    正規表現は使用しない。

    Args:
        source: Pythonソースコード文字列

    Returns:
        ランドマーク行のリスト
    """
    landmarks: List[str] = []
    try:
        tree = ast.parse(source)
        for node in ast.walk(tree):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                line_num = node.lineno
                src_lines = source.splitlines()
                if 0 < line_num <= len(src_lines):
                    landmarks.append(src_lines[line_num - 1])
            elif isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                line_num = node.lineno
                src_lines = source.splitlines()
                if 0 < line_num <= len(src_lines):
                    landmarks.append(f"# L{line_num}: " + src_lines[line_num - 1])
    except SyntaxError:
        logger.debug("PythonランドマークASTエラー（構文エラー）")
    return landmarks


def _extract_js_ts_landmarks(source: str) -> List[str]:
    """
    JavaScript/TypeScriptソースコードの構造的ランドマークを行パターンで抽出する。
    （ASTは使用せず、export/function/class/import 行を収集）

    Args:
        source: JS/TSソースコード文字列

    Returns:
        ランドマーク行のリスト
    """
    landmarks: List[str] = []
    keywords = ("export ", "import ", "function ", "class ", "const ", "async ")
    for i, line in enumerate(source.splitlines(), start=1):
        stripped = line.strip()
        if any(stripped.startswith(kw) for kw in keywords):
            landmarks.append(f"# L{i}: {line}")
    return landmarks


def _is_minified(content: str) -> bool:
    """先頭5行のいずれかが500文字超ならミニファイされたファイルと判定する。"""
    for line in content.splitlines()[:5]:
        if len(line) > 500:
            return True
    return False


def _is_auto_generated(content: str) -> bool:
    """ファイル先頭5行に自動生成マーカーが含まれる場合Trueを返す。"""
    header = "\n".join(content.splitlines()[:5])
    return bool(_AUTO_GENERATED_PATTERNS.search(header))


def _try_heuristic_summary(chunk: FileChunk) -> Optional[str]:
    """
    ファイルが自明な場合にLLMを使わずサマリーを返す。
    - 空ファイル / ロックファイル / 設定ファイル拡張子 / 極小ファイル
    - ミニファイされたファイル / 自動生成ファイル / テストファイル
    - インポートのみの __init__.py
    これらに当てはまらない場合はNoneを返し、呼び出し元がLLMにフォールバックする。
    """
    path = Path(chunk.path)
    content = chunk.content
    non_empty = [l for l in content.splitlines() if l.strip()]

    if not non_empty:
        return "空のファイル"

    if path.name in _LOCK_FILE_NAMES:
        return "依存関係のロックファイル"

    if path.suffix.lower() in _HEURISTIC_EXTENSIONS:
        lang = _detect_language(path)
        return f"{lang} 設定・データファイル（{len(non_empty)} 行）"

    if _is_minified(content):
        return "ミニファイされたアセット"

    if _is_auto_generated(content):
        lang = _detect_language(path)
        return f"自動生成された {lang} ファイル"

    # テストファイルはファイル名だけでテンプレートサマリーを生成（LLM不要）
    name_lower = path.name.lower()
    if "test" in name_lower or "spec" in name_lower:
        stem = path.stem
        for suffix in (".test", ".spec", "_test", "_spec"):
            if stem.lower().endswith(suffix):
                stem = stem[: len(stem) - len(suffix)]
                break
        lang = _detect_language(path)
        return f"{lang} のテストスイート（{stem} のテスト）"

    if len(non_empty) <= _HEURISTIC_LINE_THRESHOLD:
        lang = _detect_language(path)
        return f"小さな {lang} ファイル（{len(non_empty)} 行）"

    if path.name == "__init__.py":
        non_comment = [l for l in non_empty if not l.strip().startswith("#")]
        if non_comment and all(
            l.strip().startswith(("import ", "from ")) for l in non_comment
        ):
            return "Pythonパッケージ初期化（インポート定義のみ）"

    return None


def _try_path_summary(path: Path, size: int) -> Optional[str]:
    """
    ファイルを読まずにパスとサイズだけでサマリーを決定する（Tier-0 高速パス）。
    - サイズ0（空ファイル）
    - ロックファイル名
    - 設定・アセット系拡張子（.json, .svg, .png, .woff ...）
    - テストファイル名パターン（*test*, *spec*）
    これらに当てはまらない場合はNoneを返し、ファイル読み込みへ進む。
    """
    if size == 0:
        return "空のファイル"

    if path.name in _LOCK_FILE_NAMES:
        return "依存関係のロックファイル"

    if path.suffix.lower() in _HEURISTIC_EXTENSIONS:
        lang = _detect_language(path)
        return f"{lang} 設定・データファイル"

    name_lower = path.name.lower()
    if "test" in name_lower or "spec" in name_lower:
        stem = path.stem
        for sfx in (".test", ".spec", "_test", "_spec"):
            if stem.lower().endswith(sfx):
                stem = stem[: len(stem) - len(sfx)]
                break
        lang = _detect_language(path)
        return f"{lang} のテストスイート（{stem} のテスト）"

    return None


class AnalysisService:
    """
    コードベース分析のためのインデックス構築を担当するサービスクラス。
    ファイルごとのハイブリッド読み込み・並列サマリー生成・増分再インデックスをサポートする。
    """

    def __init__(
        self,
        fs: FileSystemAdapter,
        index_adapter: IndexAdapter,
        llm: OllamaClient,
        context: ContextService,
        vector: Optional[VectorAdapter] = None,
    ) -> None:
        """
        AnalysisServiceを初期化する。

        Args:
            fs: ファイルシステムアダプター
            index_adapter: インデックスアダプター
            llm: OllamaクライアントLLMバックエンド
            context: コンテキストサービス
            vector: ベクトルインデックスアダプター（省略可能）
        """
        self._fs = fs
        self._index_adapter = index_adapter
        self._llm = llm
        self._context = context
        self._vector = vector
        # ProjectIndex のインメモリキャッシュ: {path_str: (mtime, ProjectIndex)}
        # リクエストごとのディスク読み込み・JSONパースを回避する
        self._index_cache: dict[str, tuple[float, "ProjectIndex"]] = {}

    def read_file_chunk(self, path: Path, root: Path) -> FileChunk:
        """
        ハイブリッド読み込み戦略でファイルを読み込みFileChunkを生成する。
        - ≤200行: フル読み込み (strategy=full)
        - >200行: 先頭80行 + 末尾40行 + 構造的ランドマーク (strategy=hybrid)

        Args:
            path: ファイルの絶対パス
            root: プロジェクトルート（相対パス計算用）

        Returns:
            FileChunk
        """
        mtime, size = self._fs.get_mtime_size(path)
        try:
            source = self._fs.read_text(path)
        except Exception as exc:
            logger.warning("ファイル読み込みエラー: %s — %s", path, exc)
            source = ""

        lines = source.splitlines()
        lang = _detect_language(path)
        rel_path = str(path.relative_to(root))

        if len(lines) <= _HYBRID_THRESHOLD:
            content = source
            strategy = ChunkStrategy.FULL
        else:
            head = lines[:_HYBRID_HEAD]
            tail = lines[-_HYBRID_TAIL:]
            landmarks: List[str] = []

            if lang == "python":
                landmarks = _extract_python_landmarks(source)
            elif lang in ("javascript", "typescript"):
                landmarks = _extract_js_ts_landmarks(source)

            # 重複除去してランドマークを結合
            seen = set()
            unique_landmarks: List[str] = []
            for lm in landmarks:
                if lm not in seen:
                    seen.add(lm)
                    unique_landmarks.append(lm)

            sections = [
                "\n".join(head),
                "... (省略) ...",
                "\n".join(tail),
            ]
            if unique_landmarks:
                sections.insert(2, "--- 構造的ランドマーク ---\n" + "\n".join(unique_landmarks))

            content = "\n".join(sections)
            strategy = ChunkStrategy.HYBRID

        return FileChunk(
            path=rel_path,
            content=content,
            strategy=strategy,
            size=size,
            mtime=mtime,
            language=lang,
        )

    def build_index(
        self,
        root: Path,
        model: str,
        on_progress: Optional[Callable[[int, int, str], None]] = None,
    ) -> Generator[dict, None, None]:
        """
        コードベース全体のインデックスを構築し、進捗をSSEイベントとして生成する。
        増分再インデックスをサポート（mtime+sizeが変化したファイルのみ再処理）。

        Args:
            root: プロジェクトルート
            model: 使用するOllamaモデル名
            on_progress: 進捗コールバック（done, total, current_file）

        Yields:
            SSEペイロード辞書
        """
        lf_dir = root / _LOCALFORGE_DIR
        index_path = lf_dir / "index.jsonl"

        if self._llm.cuda_available:
            logger.info("インデックス構築: CUDA GPU推論モード")
        else:
            logger.info("インデックス構築: CPU推論モード")

        # ベクトルインデックス初期化
        if self._vector is not None:
            try:
                self._vector.init_collection(root)
            except Exception as exc:
                logger.warning("ChromaDB初期化失敗（スキップ）: %s", exc)
                self._vector = None

        # 既存チャンクを読み込んでmtime+sizeでキャッシュを作成
        existing_chunks = self._index_adapter.load_chunks(index_path)
        chunk_cache: dict[str, FileChunk] = {
            c.path: c for c in existing_chunks
        }

        # コードファイル一覧を取得
        code_files = self._fs.list_code_files(root)
        # .localforgeディレクトリのファイルを除外
        code_files = [
            f for f in code_files
            if _LOCALFORGE_DIR not in f.parts
        ]
        total = len(code_files)

        if total == 0:
            yield {"progress": {"done": 0, "total": 0, "current_file": ""}}
            return

        yield {"progress": {"done": 0, "total": total, "current_file": ""}}

        # ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        # ファイル分類: キャッシュ済み / Tier-0(パスのみ解決) / 読み込み必要
        # ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        cached_chunks: List[FileChunk] = []
        tier0_chunks: List[FileChunk] = []   # パス・サイズだけで決定（I/O不要）
        files_needing_read: List[Path] = []  # 内容確認が必要なファイル

        for f in code_files:
            rel = str(f.relative_to(root))
            mtime, size = self._fs.get_mtime_size(f)
            cached = chunk_cache.get(rel)

            if cached and abs(cached.mtime - mtime) < 0.001 and cached.size == size and cached.summary:
                # 変更なし → キャッシュを使用
                cached_chunks.append(cached)
            else:
                summary = _try_path_summary(f, size)
                if summary is not None:
                    # Tier-0: ファイルを開かずにサマリー確定
                    tier0_chunks.append(FileChunk(
                        path=rel,
                        content="",
                        strategy=ChunkStrategy.FULL,
                        size=size,
                        mtime=mtime,
                        language=_detect_language(f),
                        summary=summary,
                        indexed_at=datetime.utcnow(),
                    ))
                else:
                    files_needing_read.append(f)

        changed_count = len(tier0_chunks) + len(files_needing_read)
        done_count = 0
        all_chunks: List[FileChunk] = list(cached_chunks)
        # 並列埋め込みフェーズ用のキュー（新規/変更チャンクを収集）
        embed_queue: List[FileChunk] = []

        # キャッシュ済みファイルをひとつずつ表示してプログレスバーを正しい位置まで進める
        for cached in cached_chunks:
            done_count += 1
            yield {"progress": {"done": done_count, "total": total, "current_file": cached.path}}

        # ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        # Tier-0: パスのみで解決できたファイルを全て先に処理
        # （設定・アセット・テストファイル — ディスクI/O不要）
        # ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        t0_since_flush = 0
        for chunk in tier0_chunks:
            all_chunks.append(chunk)
            done_count += 1
            t0_since_flush += 1
            if self._vector is not None:
                embed_queue.append(chunk)
            yield {"progress": {"done": done_count, "total": total, "current_file": chunk.path}}
            if t0_since_flush >= _INCREMENTAL_SAVE_INTERVAL:
                try:
                    self._index_adapter.save_chunks(index_path, all_chunks)
                except Exception as exc:
                    logger.warning("中間インデックス保存失敗: %s", exc)
                t0_since_flush = 0

        if t0_since_flush > 0:
            try:
                self._index_adapter.save_chunks(index_path, all_chunks)
            except Exception as exc:
                logger.warning("中間インデックス保存失敗: %s", exc)

        # ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        # Tier-1 & Tier-2: 読み込みが必要なファイルを処理
        # ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        if files_needing_read:
            # 並列ファイル読み込み（GPU有無に関係なくI/Oは8並列上限で抑制）
            max_io_workers = min(8, (os.cpu_count() or 1) * 2)
            with ThreadPoolExecutor(max_workers=max_io_workers) as io_executor:
                chunks_iter = io_executor.map(
                    lambda f: self.read_file_chunk(f, root), files_needing_read
                )
                files_to_process: List[Tuple[Path, FileChunk]] = list(
                    zip(files_needing_read, chunks_iter)
                )

            # Tier-1: コンテンツベースのヒューリスティック（ミニファイ・自動生成・行数）
            needs_llm: List[Tuple[Path, FileChunk]] = []
            t1_since_flush = 0
            for f, chunk in files_to_process:
                heuristic = _try_heuristic_summary(chunk)
                if heuristic is not None:
                    chunk.summary = heuristic
                    chunk.indexed_at = datetime.utcnow()
                    all_chunks.append(chunk)
                    done_count += 1
                    t1_since_flush += 1
                    if self._vector is not None:
                        embed_queue.append(chunk)
                    yield {"progress": {"done": done_count, "total": total, "current_file": chunk.path}}
                    if t1_since_flush >= _INCREMENTAL_SAVE_INTERVAL:
                        try:
                            self._index_adapter.save_chunks(index_path, all_chunks)
                        except Exception as exc:
                            logger.warning("中間インデックス保存失敗: %s", exc)
                        t1_since_flush = 0
                else:
                    needs_llm.append((f, chunk))

            # Tier-1完了チェックポイント（LLMフェーズ開始前に保存）
            if t1_since_flush > 0:
                try:
                    self._index_adapter.save_chunks(index_path, all_chunks)
                except Exception as exc:
                    logger.warning("中間インデックス保存失敗: %s", exc)

            # Tier-2: tree-sitter シンボル抽出（LLM呼び出しなし）
            from localforge.infrastructure.symbol_extractor import extract_symbols, symbols_to_summary
            t2_since_flush = 0
            for _f, chunk in needs_llm:
                try:
                    syms = extract_symbols(chunk.path, chunk.content, chunk.language)
                    chunk.symbols = syms
                    summary = symbols_to_summary(chunk.path, chunk.language, syms)
                    chunk.summary = summary if summary else f"{chunk.path} ({chunk.language or 'unknown'})"
                except Exception as exc:
                    logger.warning("シンボル抽出エラー: %s — %s", chunk.path, exc)
                    chunk.summary = f"{chunk.path} ({chunk.language or 'unknown'})"
                chunk.indexed_at = datetime.utcnow()
                all_chunks.append(chunk)
                done_count += 1
                t2_since_flush += 1
                if self._vector is not None:
                    embed_queue.append(chunk)
                yield {"progress": {"done": done_count, "total": total, "current_file": chunk.path}}
                if t2_since_flush >= _INCREMENTAL_SAVE_INTERVAL:
                    try:
                        self._index_adapter.save_chunks(index_path, all_chunks)
                    except Exception as exc:
                        logger.warning("中間インデックス保存失敗: %s", exc)
                    t2_since_flush = 0

            if t2_since_flush > 0:
                try:
                    self._index_adapter.save_chunks(index_path, all_chunks)
                except Exception as exc:
                    logger.warning("中間インデックス保存失敗: %s", exc)

        # インデックスを保存
        try:
            self._index_adapter.save_chunks(index_path, all_chunks)
        except Exception as exc:
            raise IndexBuildError(f"インデックス保存失敗: {exc}") from exc

        # ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        # ベクトル埋め込みフェーズ: 並列処理でChromaDBに登録
        # キャッシュ済みチャンクのうちChromaDBから欠落しているものも追加
        # enable_rag=False の場合はスキップ（CPU 専用機向け高速化オプション）
        # ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        _enable_rag = True
        try:
            import json as _json
            _cfg_path = lf_dir / "config.json"
            if _cfg_path.exists():
                _enable_rag = _json.loads(_cfg_path.read_text(encoding="utf-8")).get("enable_rag", True)
        except Exception:
            pass

        if self._vector is not None and _enable_rag:
            for cached in cached_chunks:
                if cached.summary and self._vector.needs_reembedding(cached):
                    embed_queue.append(cached)

            if embed_queue:
                embed_total = len(embed_queue)
                embed_done = 0
                yield {"status": f"ベクトルインデックス構築中: 0/{embed_total}"}

                _vec = self._vector

                def _do_embed(chunk: FileChunk) -> None:
                    try:
                        if _vec.needs_reembedding(chunk):
                            _vec.upsert_chunk(chunk)
                    except Exception as exc:
                        logger.warning("埋め込みエラー (%s): %s", chunk.path, exc)

                # CPU推論では埋め込みも直列化してCPUコア競合を避ける
                _embed_workers = 4 if self._llm.cuda_available else 1
                with ThreadPoolExecutor(max_workers=_embed_workers) as embed_ex:
                    futures = {embed_ex.submit(_do_embed, c): c for c in embed_queue}
                    for future in as_completed(futures):
                        future.result()
                        embed_done += 1
                        yield {"status": f"ベクトルインデックス構築中: {embed_done}/{embed_total}"}

                yield {"status": "ベクトルインデックス完了"}

        # 変更が10%未満の増分再インデックス時はProjectIndex再生成をスキップ
        pi_path = lf_dir / "project_index.json"
        existing_index = self._index_adapter.load_index(pi_path)
        should_regenerate = (
            existing_index is None
            or (changed_count / max(total, 1)) > 0.1
        )

        if should_regenerate:
            project_index = self._build_project_index(root, model, all_chunks)
        else:
            logger.info(
                "ProjectIndex再生成をスキップ（変更率 %.1f%% <= 10%%）",
                changed_count / max(total, 1) * 100,
            )
            existing_index.file_chunks = all_chunks
            existing_index.total_files = len(all_chunks)
            existing_index.indexed_files = len(all_chunks)
            existing_index.updated_at = datetime.utcnow()
            project_index = existing_index

        self._index_adapter.save_index(pi_path, project_index)
        self.invalidate_index_cache(root)

        yield {"progress": {"done": total, "total": total, "current_file": "完了"}}
        yield {"done": True}

    def _build_project_index(
        self,
        root: Path,
        model: str,
        chunks: List[FileChunk],
    ) -> ProjectIndex:
        """
        ファイルチャンクからProjectIndexを構築する内部メソッド。

        Args:
            root: プロジェクトルート
            model: 使用するモデル名
            chunks: FileChunkのリスト

        Returns:
            ProjectIndex
        """
        # ファイルツリーのテキスト表現
        folder_tree = self._build_tree_text(root)

        # ルート設定ファイルの内容
        root_config_content = self._read_root_configs(root)

        # サマリーリスト
        file_summaries = [
            (c.path, c.summary or "") for c in chunks if c.summary
        ]

        # ProjectIndex概要をLLMで生成
        prompt = self._context.build_project_index_prompt(
            file_summaries=file_summaries,
            folder_tree=folder_tree,
            root_configs=root_config_content,
        )
        try:
            summary = self._llm.generate_sync(model, prompt).strip()
        except Exception as exc:
            logger.error("ProjectIndex概要生成エラー: %s", exc)
            summary = f"プロジェクト概要の生成に失敗しました: {exc}"

        return ProjectIndex(
            project_root=str(root),
            project_name=root.name,
            summary=summary,
            file_chunks=chunks,
            total_files=len(chunks),
            indexed_files=len(chunks),
            updated_at=datetime.utcnow(),
        )

    def _build_tree_text(self, root: Path, prefix: str = "", path: Optional[Path] = None) -> str:
        """
        ディレクトリツリーをUnicodeボックス文字で表現する内部メソッド。

        Args:
            root: ルートディレクトリ
            prefix: インデントプレフィックス
            path: 現在のパス（省略時はroot）

        Returns:
            ツリーテキスト
        """
        if path is None:
            path = root

        skip_dirs = {".git", ".localforge", "__pycache__", "node_modules", ".venv", "venv"}
        try:
            entries = sorted(path.iterdir(), key=lambda p: (p.is_file(), p.name))
        except PermissionError:
            return ""

        lines = []
        filtered = [e for e in entries if not (e.is_dir() and e.name in skip_dirs)]

        for i, entry in enumerate(filtered):
            is_last = i == len(filtered) - 1
            connector = "└── " if is_last else "├── "
            lines.append(f"{prefix}{connector}{entry.name}")
            if entry.is_dir():
                extension = "    " if is_last else "│   "
                subtree = self._build_tree_text(root, prefix + extension, entry)
                if subtree:
                    lines.append(subtree)

        return "\n".join(lines)

    def _read_root_configs(self, root: Path) -> str:
        """
        ルートディレクトリの設定ファイルを読み込む内部メソッド。

        Args:
            root: プロジェクトルート

        Returns:
            設定ファイルの内容文字列（複数ファイルを結合）
        """
        config_names = [
            "package.json", "pyproject.toml", "setup.py", "Cargo.toml",
            "go.mod", "pom.xml", "build.gradle", "Makefile",
            "docker-compose.yml", "docker-compose.yaml",
        ]
        parts = []
        for name in config_names:
            config_path = root / name
            if config_path.exists():
                try:
                    content = config_path.read_text(encoding="utf-8", errors="replace")
                    parts.append(f"--- {name} ---\n{content[:500]}")
                except OSError:
                    pass
        return "\n\n".join(parts)

    def load_project_index(self, root: Path) -> Optional[ProjectIndex]:
        """
        保存済みのProjectIndexを読み込む。
        mtime が変化していない場合はインメモリキャッシュを返してディスクI/Oを省略する。

        Args:
            root: プロジェクトルート

        Returns:
            ProjectIndex（存在しない場合はNone）
        """
        pi_path = root / _LOCALFORGE_DIR / "project_index.json"
        key = str(pi_path)
        try:
            current_mtime = pi_path.stat().st_mtime if pi_path.exists() else 0.0
        except OSError:
            current_mtime = 0.0

        cached = self._index_cache.get(key)
        if cached is not None:
            cached_mtime, cached_index = cached
            if abs(cached_mtime - current_mtime) < 0.001:
                return cached_index

        index = self._index_adapter.load_index(pi_path)
        if index is not None:
            self._index_cache[key] = (current_mtime, index)
        return index

    def invalidate_index_cache(self, root: Path) -> None:
        """ProjectIndex キャッシュを無効化する（インデックス再構築後に呼び出す）。"""
        key = str(root / _LOCALFORGE_DIR / "project_index.json")
        self._index_cache.pop(key, None)

    def migrate_vector_index(self, root: Path) -> Generator[dict, None, None]:
        """
        既存のJSONLインデックスからChromaDBベクトルインデックスへ移行する。
        サマリーが存在するチャンクのみ埋め込みを生成する。
        移行中は進捗をSSEイベントとして生成する。

        Args:
            root: プロジェクトルート

        Yields:
            SSEペイロード辞書
        """
        if self._vector is None:
            yield {"error": "VectorAdapterが設定されていません"}
            return

        lf_dir = root / _LOCALFORGE_DIR
        index_path = lf_dir / "index.jsonl"
        chunks = self._index_adapter.load_chunks(index_path)

        if not chunks:
            yield {"error": "インデックスが見つかりません。先にインデックスを構築してください。"}
            return

        try:
            self._vector.init_collection(root)
        except Exception as exc:
            yield {"error": f"ChromaDB初期化エラー: {exc}"}
            return

        chunks_with_summary = [c for c in chunks if c.summary]
        total = len(chunks_with_summary)
        yield {"progress": {"done": 0, "total": total, "current_file": ""}}

        done = 0
        for chunk in chunks_with_summary:
            if self._vector.needs_reembedding(chunk):
                self._vector.upsert_chunk(chunk)
            done += 1
            yield {"progress": {"done": done, "total": total, "current_file": chunk.path}}

        yield {"progress": {"done": total, "total": total, "current_file": "完了"}}
        yield {"done": True}

    def get_top_chunks_semantic(
        self,
        chunks: List[FileChunk],
        query: str,
        top_n: int = 15,
    ) -> List[FileChunk]:
        """
        セマンティック検索でFileChunkをランキングして上位N件を返す。
        VectorAdapterが利用可能な場合は埋め込みベクトル検索を使用し、
        そうでない場合はキーワードフォールバックを使用する。

        Args:
            chunks: 全FileChunkのリスト
            query: 検索クエリ文字列
            top_n: 返す件数

        Returns:
            上位N件のFileChunkリスト
        """
        if self._vector is not None and self._vector.is_initialized():
            return self._vector.get_top_chunks_semantic(chunks, query, top_n)
        # ChromaDB 未使用時は BM25 にフォールバック（旧キーワードカウントより高精度）
        from localforge.infrastructure.bm25_adapter import get_top_chunks_bm25
        return get_top_chunks_bm25(chunks, query, top_n)

    def get_top_chunks_by_keywords(
        self,
        chunks: List[FileChunk],
        query: str,
        top_n: int = 5,
    ) -> List[FileChunk]:
        """
        BM25 でファイルチャンクをランキングして上位 N 件を返す。
        旧キーワードカウント実装を BM25 に置き換え。

        Args:
            chunks: 全 FileChunk のリスト
            query: 検索クエリ文字列
            top_n: 返す件数

        Returns:
            上位 N 件の FileChunk リスト
        """
        from localforge.infrastructure.bm25_adapter import get_top_chunks_bm25
        return get_top_chunks_bm25(chunks, query, top_n)
